services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=bitpin_project.settings
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bitpin_db
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bitpin_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

#  k6:
#    image: grafana/k6:latest
#    command: run /tests/load_test.js
#    volumes:
#      - ./tests:/tests
#    depends_on:
#      - web
#    networks:
#      - default

volumes:
  postgres_data:
  redis_data: